namespace Converter.FileStructures.BMP
{
  public enum BMP_DIB_HEADER_TYPE
  {
    NULL,
    BITMAPCOREHEADER = 12,
    OS22XBITMAPHEADER16B = 16,
    BITMAPINFOHEADER = 40,
    BITMAPV2INFOHEADER = 52,
    BITMAPV3INFOHEADER = 56,
    OS22XBITMAPHEADER64B = 64,
    BITMAPV4INFOHEADER = 108,
    BITMAPV5INFOHEADER = 124
  }

  public enum BMP_COMPRESSION
  {
    BI_RGB = 0,
    BI_RLE8 = 1,
    BI_RLE4 = 2,
    BI_BITFIELDS = 3,
    BI_JPEG = 4,
    BI_PNG = 5,
    BI_ALPHABITFIELDS = 6,
    BI_CMYK = 11,
    BI_CMYKRLE8 = 12,
    BI_CMYKRLE4 = 13
  }
}
