// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0302:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PdfParser.ParseCrossReferenceTable(System.IO.Stream,System.UInt64)")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "This is speciifically disabled because ternary operators are only used when trying to decide between allocating array data on the stack or on the heap and it has to be done at the time or it won't compile", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseResourceDictionary(Converter.FileStructures.PDF.PDFFile,System.ValueTuple{System.Int32,System.Int32},Converter.FileStructures.PDF.PDF_ResourceDict@)")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseColorSpaceStreamAndDictionary(Converter.FileStructures.PDF.PDFFile,System.ValueTuple{System.Int32,System.Int32},Converter.FileStructures.PDF.PDF_ColorSpaceDictionary@)")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseColorSpaceIRDictionary(Converter.FileStructures.PDF.PDFFile,System.ReadOnlySpan{System.Byte},System.Boolean,System.Collections.Generic.List{Converter.FileStructures.PDF.PDF_ColorSpaceData}@)~System.Int32")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseFontIRDictionary(Converter.FileStructures.PDF.PDFFile,System.ReadOnlySpan{System.Byte},System.Boolean,System.Collections.Generic.List{Converter.FileStructures.PDF.PDF_FontData}@)~System.Int32")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseFontDescriptor(Converter.FileStructures.PDF.PDFFile,System.ValueTuple{System.Int32,System.Int32},Converter.FileStructures.PDF.PDF_FontDescriptor@)")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseRootPageTree(Converter.FileStructures.PDF.PDFFile)")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.FillAllPageTreeAndInformation(System.ValueTuple{System.Int32,System.Int32},System.Collections.Generic.List{Converter.FileStructures.PDF.PDF_PageTree},System.Collections.Generic.List{Converter.FileStructures.PDF.PDF_PageInfo},Converter.FileStructures.PDF.PDFFile)")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseCatalogDictionary(Converter.FileStructures.PDF.PDFFile)")]
[assembly: SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Pending>", Scope = "member", Target = "~M:Converter.Parsers.PDF.PdfParser.ParseFontDictionary(Converter.FileStructures.PDF.PDFFile,System.ReadOnlySpan{System.Byte},Converter.FileStructures.PDF.PDF_FontInfo@)")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "It randomly bugged out and enabled this as errors in intellisense, so i am disabling it forcefuly.", Scope = "module")]
